---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
  schedule:
    - cron: "0 0 * * 3"

jobs:
  test_bullseye:
    name: Test Debian Bullseye Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "[TEST] Build Debian 11 (Bullseye) Image"
        run: docker build -t test-docker-11 -f 11-slim/Dockerfile .

      - name: "[TEST] Run Debian 11 (Bullseye) Image"
        run: docker run --name test-docker-11 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro test-docker-11

      - name: "[TEST] Verify Debian 11 (Bullseye) Image"
        run: docker exec --tty test-docker-11 env TERM=xterm systemctl status
      
      # - uses: azure/container-scan@v0
      #   with:
      #     image-name: test-docker-11
      #     severity-threshold: MEDIUM

  test_buster:
    name: Test Debian Buster Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "[TEST] Build Debian 10 (Buster) Image"
        run: docker build -t test-docker-10 -f 10-slim/Dockerfile .

      - name: "[TEST] Run Debian 10 (Buster) Image"
        run: docker run --name test-docker-10 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro test-docker-10

      - name: "[TEST] Verify Debian 10 (Buster) Image"
        run: docker exec --tty test-docker-10 env TERM=xterm systemctl status
      
      # - uses: azure/container-scan@v0
      #   with:
      #     image-name: test-docker-10
      #     severity-threshold: MEDIUM

  release_bullseye:
    name: Release Bullseye
    runs-on: ubuntu-latest
    needs: test_bullseye
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./11-slim
          file: ./11-slim/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: yuriclopes/debian-systemd:11-slim

  release_buster:
    name: Release Buster
    runs-on: ubuntu-latest
    needs: test_buster
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./10-slim
          file: ./10-slim/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: yuriclopes/debian-systemd:10-slim