---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 3"

jobs:
  test:
    name: Test Images
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "[TEST] Build Debian 11 (Bullseye) Image"
        run: docker build -t test-docker-11 -f 11-slim/Dockerfile .
      
      - name: "[TEST] Scan Debian 11 (Bullseye) Image"
        run: docker scan --severity=medium test-docker-11

      - name: "[TEST] Run Debian 11 (Bullseye) Image"
        run: docker run --name test-docker-11 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro test-docker-11

      - name: "[TEST] Verify Debian 11 (Bullseye) Image"
        run: docker exec --tty test-docker-11 env TERM=xterm systemctl status

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: ./11-slim
          file: ./11-slim/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: debian-systemd:11-slim